Update iOS docs with regards to how to use APNS entitlements
sinch/docs pull request #161
Opened 2020-09-17 11:41 UTC by dmipon

2020-09-17 13:29 UTC, GiovanniBeriSinch requested changes

2020-09-17 13:29 UTC, GiovanniBeriSinch commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +Typically a _Debug_ build will be code signed with a _Development_ provisioning profile and thus `SINAPSEnvironmentDevelopment` should be used. And typically a _Release_ build will be code signed wit
typo: "selecing"->"selecting", in all occurrences of this sentence

2020-09-17 13:29 UTC, GiovanniBeriSinch commented on docs/tutorials/tutorials-ios/ios-managed-push-tutorial.md
>  Here you can see we’re setting the APS Environment to automatic, our delegate, and then the desired push type to automatic. When automatic is available, use it\!
"we’re setting the APS Environment to automatic"

You should update this part as well

2020-09-17 13:29 UTC, GiovanniBeriSinch commented on docs/video/video-for-ios/video-ios-local-and-remote-push-notifications.md
>  to the APS _Production_ environment.
not related to your change: this newline shouldn't be here

2020-09-17 13:29 UTC, GiovanniBeriSinch commented on docs/tutorials/tutorials-ios/ios-managed-push-tutorial.md
>  Here you can see we’re setting the APS Environment to automatic, our delegate, and then the desired push type to automatic. When automatic is available, use it\!
and what about the "automatic push type"? Is it still valid?

2020-09-17 15:22 UTC, dmipon commented on docs/tutorials/tutorials-ios/ios-managed-push-tutorial.md
>  Here you can see we’re setting the APS Environment to automatic, our delegate, and then the desired push type to automatic. When automatic is available, use it\!
`automatic push type` is still part of 4.2.5 so i will leave it

2020-09-17 15:43 UTC, GiovanniBeriSinch commented
If if checkout your branch and I `grep` for `SINAPSEnvironmentAutomatic` I see there are a bunch of occurrences in `docs/*/reference/html/...` folder:
```
└─ rg -i SINAPSEnvironmentAutomatic
docs/video/video-for-ios/reference/html/Constants/SINAPSEnvironment.html
95:<p>The macro <code>SINAPSEnvironmentAutomatic</code> can be used to specify SINAPSEnvironment based on the type of build.

docs/video/video-for-ios/reference/html/Protocols/SINManagedPush.html
120:    self.push = [Sinch managedPushWithAPSEnvironment:SINAPSEnvironmentAutomatic]

docs/voice/voice-ios-cloud/reference/html/Constants/SINAPSEnvironment.html
95:<p>The macro <code>SINAPSEnvironmentAutomatic</code> can be used to specify SINAPSEnvironment based on the type of build.

docs/voice/voice-for-ios/reference/html/Protocols/SINManagedPush.html
120:    self.push = [Sinch managedPushWithAPSEnvironment:SINAPSEnvironmentAutomatic]

docs/voice/voice-for-ios/reference/html/Constants/SINAPSEnvironment.html
95:<p>The macro <code>SINAPSEnvironmentAutomatic</code> can be used to specify SINAPSEnvironment based on the type of build.
```
Do you know if you also have to take care of that?

2020-09-17 16:57 UTC, dmipon commented
@GiovanniBeriSinch It is refense documentation that is generated from Source code. We will take care of that when we update SDK to newer version

2020-09-18 07:56 UTC, GiovanniBeriSinch approved these changes

2020-09-18 08:44 UTC, reddvl1980 commented
> @GiovanniBeriSinch It is reference documentation that is generated from Source code. We will take care of that when we update SDK to newer version

@dmipon , if changes are needed in the reference, let's update it here as well.

2020-09-18 14:42 UTC, GiovanniBeriSinch commented
All changes of last commit are generated automatically, right. If this is the case, LGTM

2020-09-28 15:48 UTC, merged