Clarify iOS app use cases
sinch/docs pull request #164
Opened 2020-09-22 11:07 UTC by dmipon

Add example which clarifies VoIP certificate upload

2020-09-22 11:42 UTC, GiovanniBeriSinch requested changes
some minor rewording/typos, and a more relevant question about voip certs

2020-09-22 11:42 UTC, GiovanniBeriSinch commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +Miss match in APNS environment settings and signing identity in one or both iOS apps will result in ability to make a call from the doctor app to the patient app.
typo: 
```suggestion
Mismatch in APNS environment settings and signing identity in one or both iOS apps will result in ability to make a call from the doctor app to the patient app.
```

2020-09-22 11:42 UTC, GiovanniBeriSinch commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +Miss match in APNS environment settings and signing identity in one or both iOS apps will result in ability to make a call from the doctor app to the patient app.
I guess, typo:
```suggestion
Miss match in APNS environment settings and signing identity in one or both iOS apps will result in inability to make a call from the doctor app to the patient app.
```

2020-09-22 11:42 UTC, GiovanniBeriSinch commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +Suppose that we have two Sinch Apps, SApp1 and SApp2 respectively and only one iOS app. If you want to make a call from iOS app with SApp1 to iOS app with SApp2 you need to generate VoIP certificate
It would be nice if you had a real life example of this scenario, in a similar fashion to the doctor/patient app of the previous case

2020-09-22 11:42 UTC, GiovanniBeriSinch commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +Suppose that we have two Sinch Apps, SApp1 and SApp2 respectively and only one iOS app. If you want to make a call from iOS app with SApp1 to iOS app with SApp2 you need to generate VoIP certificate
> generate VoIP certificate for iOS app bundle ID and upload it to the caller app in *Sinch Developer Portal*

in the doc/patient scenario you mention before, you wrote that the cert has to be uploaded for the patient app i.e. the **callee** app, while here you mention it should be done for the **caller** app.

Is it intended? Am I missing something?

2020-09-22 11:42 UTC, GiovanniBeriSinch commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +> ⚠️ Note that both iOS apps should be signed using either *Apple Development Certificate* or *iOS Distribution Certificate*. Chosen certificate must match ANPS environment setting provided to Sinch
I'd reword it like this:
```suggestion
> ⚠️ Note that both iOS apps should be signed using either *Apple Development Certificate* or *iOS Distribution Certificate*. Chosen certificate must match ANPS environment setting provided to Sinch SDK when `SINManagedPush` is created: if you sign using *Apple Development Certificate* please provide `SINAPSEnvironmentDevelopment`, if you sign using *iOS Distribution Certificate* please provide `SINAPSEnvironmentProduction`.
```

2020-09-22 11:49 UTC, dmipon commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +Suppose that we have two Sinch Apps, SApp1 and SApp2 respectively and only one iOS app. If you want to make a call from iOS app with SApp1 to iOS app with SApp2 you need to generate VoIP certificate
In the first case Sinch APP is the only one and it matters for which bundle ID we generate the VoIP certificate. In the second case bundle ID is the one and it matters into which Sinch APP we upload the certificate

2020-09-22 12:03 UTC, christoffer-a-sinch commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +Suppose that we have two Sinch Apps, SApp1 and SApp2 respectively and only one iOS app. If you want to make a call from iOS app with SApp1 to iOS app with SApp2 you need to generate VoIP certificate
I'm myself not so keen on using the doctor/patient concrete example, I think I'd prefer just _A_ and _B_... But maybe more importantly we should at least be consistent in the two examples. 

When referring to "Sinch Apps", use _Sinch Applications_ . E.g. we tend to spell out full _Application_ in when referencing a _Sinch Application_, but use just "app" if speaking of very generic apps like "iOS app".

2020-09-22 12:03 UTC, christoffer-a-sinch commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +Suppose that we have two Sinch Apps (in Sinch Portal), Driver App and Passenger App and only one iOS app.
To a customer that is not in the ride-hailing segment I think this "driver" and "rider" examples will actually not make sense. I think we should make it generic and only speak of "Application A" and "Application B". And be consistent with that in both examples.

2020-09-22 12:04 UTC, christoffer-a-sinch commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +You want a doctor to be able to call a patient. You need to generate *VoIP certificate* for the app with `PatBundleID` and upload it to *Sinch Developer Portal* for the *Sinch Application* which key
It is only in the 4.x SDK we had a factory method that allowed injecting secret. In the 5.x sample apps we only allow JWT auth. Though the secret is technically in the sample app, is not intended like that in production deployments. So, I think we should just remove the reference to `secret` here and only speak of _Sinch Application_ and _Application Key_.

2020-09-22 14:51 UTC, dmipon commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +1. Multiple Sinch Applications, one iOS app (one Bundle ID)
Nope. Markdown renderer will display it correctly regardless of what is here. It's a feature to avoid confusion when add/remove/change positions of items

2020-09-22 14:52 UTC, dmipon commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +Suppose that we have two Sinch Apps (in Sinch Portal), Driver App and Passenger App and only one iOS app.
Heh :) okay i'll fix it back again :)

2020-09-23 15:56 UTC, GiovanniBeriSinch commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +iOS app could be build with App-A application key or App-B application key.
typo
```suggestion
iOS app could be built with App-A application key or App-B application key.
```

2020-09-23 15:56 UTC, GiovanniBeriSinch commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +Suppose that we have two Sinch Apps, SApp1 and SApp2 respectively and only one iOS app. If you want to make a call from iOS app with SApp1 to iOS app with SApp2 you need to generate VoIP certificate
so, is the general rule:
"the **caller Sinch App** needs to have a certificate of the **callee iOS app**"
?

I trust the comments you wrote are correct, I am just trying to understand it myself 😃

2020-09-23 15:57 UTC, GiovanniBeriSinch requested changes
typo

2020-09-28 15:49 UTC, dmipon commented on docs/voice/voice-for-ios/voice-ios-push-notifications-callkit.md
> +Suppose that we have two Sinch Apps, SApp1 and SApp2 respectively and only one iOS app. If you want to make a call from iOS app with SApp1 to iOS app with SApp2 you need to generate VoIP certificate
yes

2020-10-12 09:59 UTC, merged