Resolves #VERJ-7 Added basic docs regarding JVM Verification SDK
sinch/docs pull request #268
Opened 2021-01-18 13:24 UTC by olllo123

2021-01-20 07:18 UTC, Crozin requested changes

2021-01-20 07:18 UTC, Crozin commented on docs/verification/verification-for-jvm/verification-jvm-first-time-setup.md
> +```text
Shouldn't we suggest XML formatting?

2021-01-20 07:18 UTC, Crozin commented on docs/verification/verification-for-jvm/verification-jvm-first-time-setup.md
> +  <version>*.*.*</version>
I think we should specify most recent version unless that's a convention? Yes, it might be annoying from time to time. Or at least most recent major version.

2021-01-22 05:53 UTC, olllo123 commented on docs/verification/verification-for-jvm/verification-jvm-first-time-setup.md
> +  <version>*.*.*</version>
We can do this like this however even on github readmes many repos don't specify the version. 
They just point to a place where it can be checked, that how the docs for Android and iOS do as well.

2021-01-22 05:56 UTC, olllo123 commented on docs/verification/verification-for-jvm/verification-jvm-first-time-setup.md
> +```text
True, done :)

2021-01-27 19:42 UTC, JEllis72 approved these changes

2021-01-27 19:43 UTC, JEllis72 approved these changes

2021-02-03 16:06 UTC, Crozin approved these changes

2021-02-17 09:31 UTC, merged